### ISSUE TITLE
Errors on iPhone 

### ISSUE THREAD

**Issue by 2clarks** [zacharee/HINTControl#58]
When disabling WiFi (both) on app and save, it instantly errors out with a listt of codes or something similar. I, at that point, have to hard reset T-Mobile modem and Eero 6

**Comment by zacharee** [comment]
I can't do much about this without knowing which gateway and what the errors are. You don't need to reset your Eero.

**Comment by 2clarks** [comment]
I am using the T-Mobile Arcadyan KVD21 5G gateway.  Software version 1.00.22These are just two of what I encountered. I will send an additional later. Could just be operator error too. Thank you. Sent from my iPhoneOn Jul 15, 2024, at 7:54 PM, Zachary Wander ***@***.***> wrote:﻿
I can't do much about this without knowing which gateway and what the errors are. You don't need to reset your Eero.
