### ISSUE TITLE
*Not a Bug* Change repository name/ update iOS code on app store

### ISSUE THREAD

**Issue by pigs-on-the-wing** [zacharee/HINTControl#65]
Not an issue/ bug, but wanted to see if this change can be made to benefit others who search/ land here...

1. Since the code now supports all available T-Mo 5G gateways Arcadyn's, Sage/Ser com, Nokia (and not just KVD21), perhaps change the repository name??. When I first googled and landed here on KVD21, was a little confused

2. Also iOS seems to be way outdated (3+ months old lagging at 1.10.5) and 1.12 is out (even for macOS)

**Comment by zacharee** [comment]
I renamed the repository. I've only been able to submit iOS builds to TestFlight since I'm running the macOS 15 beta, but I was able to set up Xcode Cloud to build the app for stable release.
