### ISSUE TITLE
HINT UI hangs with version 1.12.x on macOS Sonoma 14.5

### ISSUE THREAD

**Issue by pigs-on-the-wing** [zacharee/HINTControl#67]
Happened with 1.12.1, upgraded to 1.12.2 ... same issue
Have to force quit and freezes again
macOS Sonoma 14.5
HINT Control 1.12.1/2

**Comment by zacharee** [comment]
Is this on Intel or Apple Silicon? Are you using the iOS version or the DMG from the Releases page?

**Comment by pigs-on-the-wing** [comment]
Apple silicon - M2 Air
System prompted me to upgrade to latest version and went through the install/ relaunch

**Comment by zacharee** [comment]
This should be fixed in 1.12.3

**Comment by pigs-on-the-wing** [comment]
HINT sure is purring away!!
Thanks Zach
