### ISSUE TITLE
App name incorrect 

### ISSUE THREAD

**Issue by thepcwiz1012** [zacharee/HINTControl#72]
I have the latest update from google play and it shows TaskerPluginLibrary as the app name in the launcher. I reinstalled the app from google play and didn't fix the issue.

**Comment by thepcwiz1012** [comment]
![Screenshot_20240812-232258](https://github.com/user-attachments/assets/09f29029-bf42-4f1f-9a26-c208510d1bb5)

**Comment by zacharee** [comment]
This is fixed in 1.13.0.
