### ISSUE TITLE
Add antenna toggle capability to HINT (Int <-> Ext)

### ISSUE THREAD

**Issue by pigs-on-the-wing** [zacharee/HINTControl#73]
The T-Mobile Arcadyn TMOG4AR has physical external antenna ports and allows the user to toggle between Internal and External antennas (if connected) using the physical buttons on the front of the 5G gateway

I'm assuming the same capability to switch between Int/ Ext can be accomplished via software in Hint Control
If you want to test the code, I am happy to help

If curious why I would ask for this - The stock internal antenna gets me far higher download speeds (450-700 Mbps), but pathetic uploads (1-9 Mbps). The External antenna (Waveform QuadPro) gets me upto 40Mbps upload speeds which I seldom need - but it comes at the expense of bringing the download speed to <200 Mbps... and yes I have extensively troubleshooted with techs at waveform trying out various port configurations, placements etc, but hasn't helped
 
Being able to switch antennas with HINT would be awesome and very convenient

Also, why is it called HINT, this is a Tmo 5G gateway killer management app - Perhaps rename as T5G HubControl or T5G CommandCenter <grin>

**Comment by zacharee** [comment]
The known API only has a way to show the currently-used antenna. It doesn't have a way to change it.
