### ISSUE TITLE
Consider adding warning when attempting to disable both bands

### ISSUE THREAD

**Issue by jaredbrogan** [zacharee/HINTControl#75]
I just experienced the same issue as described in this reddit post: https://old.reddit.com/r/tmobileisp/comments/1ejuz98/g4_gateway_stuck_powering_on/

When using the gateway (at least the G4SE model) without its router enabled whatsoever and utilizing a separate router, this results in the gateway being stuck on a "Powering up" screen after the next reboot. Being that this is only affecting the wifi capability of the gateway, the wired connection to my separate router still works just fine. When this is encountered, a factory reset is required to fix the issue. Once reset and reconfigured, you can then hide the gateway's SSID in the T-Mobile/T Life app and then **only** disable the 2.4GHz band in HINT. Apparently the 5GHz band is required to stay on, otherwise the "Powering up" issue happens.

I'm not sure if this was caused by a recent firmware update (currently on version `1.03.14`) as I'm a new user of TMHI, but seems like it's a possibility at least.

For added context when the issue is happening -- HINT's Wi-Fi section fails to load giving the following response body:
```
{
  "result": {
    "error": "SetFailed",
    "message": "WiFi driver is busy. Please try again later.",
    "statusCode": 408
  }
}
```

**Comment by zacharee** [comment]
This is a bug in the firmware and it seems to be happening on every unified API model (KVD21 and later). I think I might make it so it's impossible to turn off the 5GHz band for unified API gateways and show an informational dialog.

**Comment by jaredbrogan** [comment]
Yeah, probably for the best given the impact.

**Comment by zacharee** [comment]
1.13.2 makes it impossible to turn off 5GHz WiFi (much to the chagrin of Play Store reviewers apparently), with a message explaining why.

**Comment by cyoung1228** [comment]
Sorry for a comment on a closed issue, but I think I might've found a _kind of_ workaround to get the newer devices to broadcast no wifi signal. Though, I'm not 100% sure it's not still broadcasting networks as I don't really have any devices to scan with except apple devices and a Shield Tv.

So what I did was (on a TMO-G4AR that I rebooted between each step):

- Set the gateway's default network in the TMHI app or T-Life app to just 2.4ghz
- Set the network as hidden
- Using HINT Control (connected to my wifi 6E router in AP mode wired to the gateway) disabled the 2.4ghz radio
- Checked with the wifi scanning apps I had and seemingly no networks were being broadcast, except for my wifi 6E router's

If anyone can fully verify that this actually accomplishes the desired result of the TMO gateway radios not broadcasting anything, it might be worth noting somewhere in the app so the Google Play Store complainers can stop complaining.

**Comment by homeontherocks** [comment]
I can confirm that cyoung1228's suggestion does work for me.  If I type in the SSID it won't allow me to enter a password so I assume the SSID is not broadcasting and the radios are off.  Thanks for the suggestion!

**Comment by neeravmodi** [comment]
I can also confirm that cyoung1228's method works.  I have also confirmed through channel scans that the SSID is not hidden either.  It's truly turned off.

**Comment by CircuitGuy** [comment]
TMO-G5AR Model seems to break @cyoung1228 workaround. 
 
I set ONLY 2.4 GHz in T-LIFE
Then disable 2.4 in HINT. 
HINT shows all radios disabled 

Wifiman (scanner app) shows that 5 GHz is still broadcasting from the hotspot.
 
Edit: but it's intermittent?!
