### ISSUE TITLE
Prevent disabling 5GHz WiFi on newer gateways.

### ISSUE THREAD

**Issue by logicito** [zacharee/HINTControl#77]
I know this is not an issue, but I didn't find another place to ask, what is the reason for the last change "- Prevent disabling 5GHz WiFi on newer gateways." in the latest release? Is it that now we will not be able to disable Wifi? I have one of the newest gateway, the G4AR, and I have disabled Wifi 2.4GHz and 5GHz a long time ago, and as far as I know I haven't noticed any problems, apart for more frequent auto reboots, weekly vs never before, please could you share more information, thank you

**Comment by zacharee** [comment]
Context is here: https://github.com/zacharee/HINTControl/issues/75
