### ISSUE TITLE
ERROr: Java_Home variable

### ISSUE THREAD

**Issue by rustygrep** [zacharee/HINTControl#78]
I am not a programmer or developer, so I am already a tad frustrated, because I don't understand why this can't just exist as simple MSI or EXE, but I digress. 

I get the Error:Java_Home is not set and no 'java' command could be found in your path error.

![image](https://github.com/user-attachments/assets/04a21426-7bff-43b7-ab43-dbf67e1d5684)

**Comment by zacharee** [comment]
There are prebuilt binaries available on the [releases](https://github.com/zacharee/HINTControl/releases) page. You can download the `*-windows-amd64.zip` file, extract it, and run the EXE inside the `bin` folder.
