### ISSUE TITLE
LTE data missing

### ISSUE THREAD

**Issue by rstilwell** [zacharee/HINTControl#79]
I have the latest version of the HINT Control App installed on my MacBook, iPhone, and iPad via their respective App Stores, as well as on my Windows machines via the msix installer/sideload method - all of these apps stopped displaying LTE information.

I rebooted my G4AR to no avail. All I see is an exclamation mark next to the LTE signal strength. 5G continues to display all the information that it should display.

Thanks in advance for looking into this and providing a great app for us to manage our TMHI gateways!

**Comment by zacharee** [comment]
Are you sure you're just not connecting in 5G standalone mode? Does the official app show any LTE info?

**Comment by rstilwell** [comment]
Looks like it might indeed be in standalone mode (first for me to actually see it in practice). Official app comes up blank when I look for cellular metrics.
