### ISSUE TITLE
HINT Control missing LTE data

### ISSUE THREAD

**Issue by pigs-on-the-wing** [zacharee/HINTControl#81]
Not sure if others are seeing this issue. LTE section in HINT is blank. Not sure if the gateway not sending data to HINT OR if T-Mo has changed the parameters and HINT needs to be updated?

Arcadyn TMO-G4AR running Software version 1.00.12, Hardware version R01
HINT Control 1.13.2

See screenshot below. Tried rebooting the gateway and waited 1+day to see if that makes a difference... no luck!

<img width="512" alt="Screenshot 2024-10-25 at 7 21 16 AM" src="https://github.com/user-attachments/assets/00bebe7a-2efb-4a3f-a56b-efe42d813dc4">

**Comment by Ctyankee9** [comment]
Factory reset your gateway, not reboot. Don't think it is something to do with this app specifically, but rather the hardware/firmware in the gateways. It will also show like that in the native T-Mobile apps.

A number of posts about it in r/tmobileisp if you use Reddit.

**Comment by pigs-on-the-wing** [comment]
Thanks @Ctyankee9 for the reddit note - I was not aware and glad to see I am not the only one seeing the blank LTE stats

Also saw another [post](https://www.reddit.com/r/tmobileisp/comments/1gc7z2y/firmware_update_coming/) about the .12 firmware update being pushed out this weekend. I'll give it a factory reset post that push...
